config/routes.rb
Rails.application.routes.draw do
  get 'profile/show'

  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'

  #resources :profiles
  resources :posts do
    member do
      get 'like'
    end
  end
  get ':user_name', to: 'profile#show', as: :profile
  get ':user_name/edit', to: 'profile#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profile#update', as: :update_profile

  get ':user_name/post', to: 'profile#new', as: :recommend_post
  post ':user_name/post', to: 'profile#build', as: :recommend_build

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	acts_as_votable
	belongs_to :user
	validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  has_many :posts, dependent: :destroy
  has_attached_file :avatar, styles: {medium: '152x152#'}
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!
	before_action :set_post, only: [:like, :destroy]

	def index 
		@posts = Post.all.order('created_at DESC')
	end

	def new 
		@post= current_user.posts.build
	end


	def create
		@post = current_user.posts.build(post_params)

        if @post.save
          flash[:success] = "Your post has been created!"
          redirect_to profile_path(current_user.user_name)
        else
          flash[:alert] = "New post couldn't be created"
          render :new
        end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	def like
	  if @post.user == current_user
	  #cant reccomend your own post!
	  else 
	    if @post.liked_by current_user
          respond_to do |format|
            format.html { redirect_to :back }
            format.js
          end
        end
      end
	end

	private

	def set_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:skill)
	end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :set
  before_action :own_profile, only: [:edit, :update]
 
  def show
  	#@user = User.find_by(user_name: params[:user_name])
  	@posts = User.find_by(user_name: params[:user_name]).posts.order(:cached_votes_up => :desc)
  end

  def new
  	@post = User.find_by(user_name: params[:user_name]).posts.build
  end

  def build
  	@post = User.find_by(user_name: params[:user_name]).posts.build(post_params)

    if @post.save
      #reccomend the post
      if @post.liked_by current_user
        respond_to do |format|
          format.html { redirect_to profile_path(@post.user.user_name) }
          format.js
          end
      end
      flash[:success] = "The new skill has been added!"
      #redirect_to profile_path(@post.user.user_name)
    else
      flash[:alert] = "The new skill couldn't be created :("
      render :new
    end
  end


  def edit
    #@user = User.find_by(user_name: params[:user_name])
  end

  def update
    #@user = User.find_by(user_name: params[:user_name])
    if @user.update(profile_params)
      flash[:success] = 'Your profile has been updated.'
      redirect_to profile_path(@user.user_name)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  private 

  def profile_params
  	params.require(:user).permit(:avatar, :bio)
  end

  before_action :authenticate_user!

  def own_profile
  	#@user = User.find_by(user_name: params[:user_name])
  	unless current_user == @user
  		flash[:alert] = "Not your profile"
  		redirect_to root_path
  	end
  end

  def set
  	@user = User.find_by(user_name: params[:user_name])
  end

  def post_params
    params.require(:post).permit(:skill)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def alert_for(flash_type)
    { success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-warning',
    notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
    end

    def profile_avatar_select(user)
      return image_tag user.avatar.url(:medium),
        id: 'image-preview',
          class: 'img-responsive img-circle profile-image' if user.avatar.exists?
            image_tag 'default-avatar.jpg', id: 'image-preview',
              class: 'img-responsive img-circle profile-image'
    end
end

module PostsHelper
  def display_likes(post)
    votes = post.votes_for.up.by_type(User)
    return list_likers(votes) if votes.size <= 4
    count_likers(votes)
  end

  private

  def count_likers(votes)
    vote_count = votes.size
    vote_count.to_s + ' recommendations'
  end

  def list_likers(votes)
    user_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        user_names.push(link_to voter.user_name,
                                profile_path(voter.user_name),
                                class: 'user-name')
      end
      user_names.to_sentence.html_safe + like_plural(votes)
    end
  end

  def like_plural(votes)
    return ' recommend this skill' if votes.count > 1
    ' recommends this skill'
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .navbar-container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
      .navbar-brand= link_to "スキル", root_path
    .collapse.navbar-collapse#bs-navbar-collapse-1
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = link_to "Your Profile", profile_path(current_user.user_name)
          %li
            = link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %li
            = link_to "Login", new_user_session_path
          %li
            = link_to "Register", new_user_registration_path

app/views/layouts/application.html.haml
%html
  %head
    %title Your Skills
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
%body
  = render 'layouts/navbar'
  .container
    -flash.each do |name, msg|
      = content_tag :div, msg, class: [:alert, alert_for(name)]
    = yield

app/views/posts/_form.html.haml
.form-wrapper
  = simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f|
    .form-group.text-center
      = f.input :skill
    .form-group.text-center
      = f.button :submit, 'Add New Skill', class: 'btn-success'

app/views/posts/_likes.html.haml
.likes{id: "likes_#{post.id}"}
  = display_likes post

app/views/posts/_post.html.haml
.posts-wrapper
  .post
    .post-head
      .thumb-img
      .user-name
        = link_to post.user.user_name, profile_path(post.user.user_name)
    %p.skill
      =post.skill
    .reccomend
      = link_to '', like_post_path(post.id), remote: true, id: "like_#{post.id}", class: "glyphicon glyphicon-plus"
    .post-bottom
      = render 'posts/likes', post: post

app/views/posts/index.html.haml
-@posts.each do |post|
  = render 'post', post: post

app/views/posts/like.js.erb
$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");

app/views/posts/new.html.haml
= render "form"

app/views/posts/unlike.js.erb
$("#like_<%= @post.id %>").removeAttr('href').attr('href', '/posts/<%= @post.id %>/like');
$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");